/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";

import type { Dummy } from "../Dummy";

export class Dummy__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<Dummy> {
    return super.deploy(overrides || {}) as Promise<Dummy>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): Dummy {
    return super.attach(address) as Dummy;
  }
  connect(signer: Signer): Dummy__factory {
    return super.connect(signer) as Dummy__factory;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Dummy {
    return new Contract(address, _abi, signerOrProvider) as Dummy;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "serviceName",
        type: "string",
      },
    ],
    name: "pay",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506101c7806100206000396000f3fe60806040526004361061001e5760003560e01c80632b66d72e14610023575b600080fd5b61003d600480360381019061003891906100b1565b61003f565b005b3460008190555050565b600061005c61005784610123565b6100f2565b90508281526020810184848401111561007457600080fd5b61007f848285610153565b509392505050565b600082601f83011261009857600080fd5b81356100a8848260208601610049565b91505092915050565b6000602082840312156100c357600080fd5b600082013567ffffffffffffffff8111156100dd57600080fd5b6100e984828501610087565b91505092915050565b6000604051905081810181811067ffffffffffffffff8211171561011957610118610162565b5b8060405250919050565b600067ffffffffffffffff82111561013e5761013d610162565b5b601f19601f8301169050602081019050919050565b82818337600083830152505050565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052604160045260246000fdfea2646970667358221220c4ff2273f470cfc10fb8a1757ff691d5bd7c2d44fd0cc9e48d48d0410b7658b664736f6c63430008000033";
