/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IPayable } from "../IPayable";

export class IPayable__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPayable {
    return new Contract(address, _abi, signerOrProvider) as IPayable;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "serviceName",
        type: "string",
      },
    ],
    name: "pay",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
];
